### ISSUE TITLE
Problem in docs.md when rendering as HTML

### ISSUE THREAD

**Issue by python33r** [merely-useful/still-magic#17]
`docs.md` shows the results of running `pydoc` by using a fragment of its HTML output, included from `reuse/trim.html`. This appears to cause a problem when rendering the page as HTML. The effect can be seen currently at https://merely-useful.github.io/still-magic/en/docs/

The issue seems to be that there is an opening `<div>` for the included fragment, but the closing `</div>` has somehow been escaped to `&lt;/div&gt;`

Related question: could included HTML fragments like this be affected by changes to the CSS used for the document? If so, might it be safer to use a screenshot as the example of `pydoc` output?

**Comment by gvwilson** [comment]
Thanks for the report - yeah, there's something weird going on there. I could include a screenshot, but I'm trying to keep things accessible for the visually impaired, so anything I can do with HTML, I'd like to. I'll dig into this one...
